name: SSH Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "-----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
        QyNTUxOQAAACAhdg7fDecpu7eM10k3eaAZDXEIQrxZxt71BJ+BGsCy8wAAAJDnCVqF5wla
        hQAAAAtzc2gtZWQyNTUxOQAAACAhdg7fDecpu7eM10k3eaAZDXEIQrxZxt71BJ+BGsCy8w
        AAAECwB15aYnpfVTjCaZebl8MVyhXXMomVAL2xq6I8Ur+x5iF2Dt8N5ym7t4zXSTd5oBkN
        cQhCvFnG3vUEn4EawLLzAAAABkdUTEFCUwECAwQFBgc=
        -----END OPENSSH PRIVATE KEY-----" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 110.142.157.72 >> ~/.ssh/known_hosts

    - name: SSH into Server
      run: ssh -o StrictHostKeyChecking=no -p 22 username@110.142.157.72 "echo 'Connected successfully!'"
